const cor = [
    { id: 1, nombre: 'Buque de Noiva', color: '#b45073', vivax: '786', imagen: '/path/to/balde_buque_de_noiva.png' },
    { id: 2, nombre: 'Jardim de Azaleias', color: '#a75187', vivax: '785', imagen: '/path/to/balde_jardim_de_azaleias.png' },
    { id: 3, nombre: 'Azul Rei', color: '#62abdb', vivax: '777', imagen: '/path/to/balde_azul_rei.png' },
    { id: 4, nombre: 'Azul Bebê', color: '#b7d5e5', vivax: '739', imagen: '/path/to/balde_azul_bebe.png' },
    { id: 5, nombre: 'Onestidade', color: '#d6dbe0', vivax: '726', imagen: '/path/to/balde_onestidade.png' },
    { id: 6, nombre: 'Rosa Branca', color: '#e7e4e4', vivax: '740', imagen: '/path/to/balde_rosa_branca.png' },
    { id: 7, nombre: 'Flor de Laranjeira', color: '#ebe4e8', vivax: '744', imagen: '/path/to/balde_flor_de_laranjeira.png' },
    { id: 8, nombre: 'Cordilheira dos Andes', color: '#edeae0', vivax: '705', imagen: '/path/to/balde_cordilheira_dos_andes.png' },
    { id: 9, nombre: 'Lago Congelado', color: '#afc7d2', vivax: '734', imagen: '/path/to/balde_lago_congelado.png' },
    { id: 10, nombre: 'Suco de Clorofila', color: '#afdf9a', vivax: '768', imagen: '/path/to/balde_suco_de_clorofila.png' },
    { id: 11, nombre: 'Mergulho no Mar', color: '#e3ebd6', vivax: '745', imagen: '/path/to/balde_mergulho_no_mar.png' },
    { id: 12, nombre: 'Açaí', color: '#834c63', vivax: '784', imagen: '/path/to/balde_acai.png' },
    { id: 13, nombre: 'Topo do Mundo', color: '#00818f', vivax: '771', imagen: '/path/to/balde_topo_do_mundo.png' },
    { id: 14, nombre: 'Azul Guache', color: '#7eafc9', vivax: '737', imagen: '/path/to/balde_azul_guache.png' },
    { id: 15, nombre: 'Pão de Ló', color: '#e3c397', vivax: '779', imagen: '/path/to/balde_pao_de_lo.png' },
    { id: 16, nombre: 'Azul Mineral', color: '#688f95', vivax: '766', imagen: '/path/to/balde_azul_mineral.png' },
    { id: 17, nombre: 'Ibiza', color: '#4c9999', vivax: 'N/A', imagen: '/path/to/balde_ibiza.png' },
    { id: 18, nombre: 'Chá de Erva Doce', color: '#e6ecc6', vivax: '749', imagen: '/path/to/balde_cha_de_erva_doce.png' },
    { id: 19, nombre: 'Ninho', color: '#c7b59c', vivax: '702', imagen: '/path/to/balde_ninho.png' },
    { id: 20, nombre: 'Cocada', color: '#d7c8b1', vivax: '719', imagen: '/path/to/balde_cocada.png' },
    { id: 21, nombre: 'Cortiça', color: '#cbbca8', vivax: '723', imagen: '/path/to/balde_cortica.png' },
    { id: 22, nombre: 'Camelo', color: '#d1bdab', vivax: 'N/A', imagen: '/path/to/balde_camelo.png' },
    { id: 23, nombre: 'Passas ao Rum', color: '#aa9385', vivax: '751', imagen: '/path/to/balde_passas_ao_rum.png' },
    { id: 24, nombre: 'Broto de Feijão', color: '#d0cac1', vivax: '710', imagen: '/path/to/balde_broto_de_feijao.png' },
    { id: 25, nombre: 'Algodão Egípcio', color: '#eae3d5', vivax: '707', imagen: '/path/to/balde_algodao_egipcio.png' },
    { id: 26, nombre: 'Miragem', color: '#d3bdb8', vivax: '724', imagen: '/path/to/balde_miragem.png' },
    { id: 27, nombre: 'Trovoada', color: '#7f889c', vivax: '765', imagen: '/path/to/balde_trovoada.png' },
    { id: 28, nombre: 'Conforto', color: '#a3aeb0', vivax: '727', imagen: '/path/to/balde_conforto.png' },
    { id: 29, nombre: 'Malha de Aço', color: '#5b6264', vivax: '792', imagen: '/path/to/balde_malha_de_aco.png' },
    { id: 30, nombre: 'Jardim do Éden', color: '#6d8481', vivax: '775', imagen: '/path/to/balde_jardim_do_eden.png' },
    { id: 31, nombre: 'Volta ao Mundo', color: '#617374', vivax: '774', imagen: '/path/to/balde_volta_ao_mundo.png' },
    { id: 32, nombre: 'Baquetas', color: '#aec1c1', vivax: '732', imagen: '/path/to/balde_baquetas.png' },
    { id: 33, nombre: 'Mantra', color: '#96a8a7', vivax: '736', imagen: '/path/to/balde_mantra.png' },
    { id: 34, nombre: 'Acrópole', color: '#a3a390', vivax: '767', imagen: '/path/to/balde_acropole.png' },
    { id: 35, nombre: 'Verde Vitoria', color: '#b9d9c4', vivax: '746', imagen: '/path/to/balde_verde_vitoria.png' },
    { id: 36, nombre: 'Creme de Menta', color: '#a5e6b8', vivax: '748', imagen: '/path/to/balde_creme_de_menta.png' },
    { id: 37, nombre: 'Cinza Fóssil', color: '#c9c4b6', vivax: '712', imagen: '/path/to/balde_cinza_fossil.png' },
    { id: 38, nombre: 'Ipê Amarelo', color: '#F4C630', vivax: '800', imagen: '/path/to/balde_ipe_amarelo.png' },
    { id: 39, nombre: 'Crômio', color: '#D1D0CA', vivax: '708', imagen: '/path/to/balde_cromio.png' },
    { id: 40, nombre: 'Nimbus', color: '#788792', vivax: '760', imagen: '/path/to/balde_nimbus.png' },
    { id: 41, nombre: 'Pó de Zinco', color: '#767F87', vivax: '763', imagen: '/path/to/balde_po_de_zinco.png' },
    { id: 42, nombre: 'Escuridão', color: '#465264', vivax: '789', imagen: '/path/to/balde_escuridao.png' },
    { id: 43, nombre: 'Margarida Primavera', color: '#FFCC00', vivax: 'N/A', imagen: '/path/to/balde_margarida_primavera.png' },
    { id: 44, nombre: 'Berimbau', color: '#B49B84', vivax: '754', imagen: '/path/to/balde_berimbau.png' },
    { id: 45, nombre: 'Capoeira', color: '#CBB59C', vivax: '725', imagen: '/path/to/balde_capoeira.png' },
    { id: 46, nombre: 'Papel Picado', color: '#D8D3CA', vivax: '706', imagen: '/path/to/balde_papel_picado.png' },
    { id: 47, nombre: 'Cashmere', color: '#9FAF96', vivax: '769', imagen: '/path/to/balde_cashmere.png' },
    { id: 48, nombre: 'Verde Folia', color: '#9FCC4B', vivax: '795', imagen: '/path/to/balde_verde_folia.png' },
    { id: 49, nombre: 'Cereja', color: '#A82939', vivax: '788', imagen: '/path/to/balde_cereja.png' },
    { id: 50, nombre: 'Verde Pout-Pourri', color: '#c5d4bc', vivax: '747', imagen: '/path/to/balde_verde_pout_pourri.png' },
    { id: 51, nombre: 'Amor', color: '#ae3b33', vivax: '787', imagen: '/path/to/balde_amor.png' },
    { id: 52, nombre: 'Mergulho de Noronha', color: '#01a89d', vivax: '770', imagen: '/path/to/balde_mergulho_de_noronha.png' },
    { id: 53, nombre: 'Bala de Cereja', color: '#efb2cc', vivax: '741', imagen: '/path/to/balde_bala_de_cereja.png' },
    { id: 54, nombre: 'Céu Californiano', color: '#c0dee7', vivax: '731', imagen: '/path/to/balde_ceu_californiano.png' },
    { id: 55, nombre: 'Noz-Moscada', color: '#decec2', vivax: '752', imagen: '/path/to/balde_noz_moscada.png' },
    { id: 56, nombre: 'Festa da Uva', color: '#673e69', vivax: 'N/A', imagen: '/path/to/balde_festa_da_uva.png' },
    { id: 57, nombre: 'Fuga do Tempo', color: '#c4b2a9', vivax: 'N/A', imagen: '/path/to/balde_fuga_do_tempo.png' },
    { id: 58, nombre: 'Pêssego', color: '#EDC4A7', vivax: '730', imagen: '/path/to/balde_pessego.png' },
    { id: 59, nombre: 'Camurça', color: '#CCB997', vivax: '753', imagen: '/path/to/balde_camurca.png' },
    { id: 60, nombre: 'Erva Doce', color: '#EBEADA', vivax: '711', imagen: '/path/to/balde_erva_doce.png' },
    { id: 61, nombre: 'Gelo', color: '#E6EAE1', vivax: '701', imagen: '/path/to/balde_gelo.png' },
    { id: 62, nombre: 'Prata', color: '#C0C0BA', vivax: '729', imagen: '/path/to/balde_prata.png' },
    { id: 63, nombre: 'Elefante', color: '#A2A29D', vivax: '761', imagen: '/path/to/balde_elefante.png' },
    { id: 64, nombre: 'Amarelo Ouro', color: '#D6C15C', vivax: '781', imagen: '/path/to/balde_amarelo_ouro.png' },
    { id: 65, nombre: 'Preto Absoluto', color: '#28292B', vivax: '799', imagen: '/path/to/balde_preto_absoluto.png' },
    { id: 66, nombre: 'Abacaxi', color: '#F3EDB3', vivax: '780', imagen: '/path/to/balde_abacaxi.png' },
    { id: 67, nombre: 'Maracujá', color: '#F8E385', vivax: '750', imagen: '/path/to/balde_maracuja.png' },
    { id: 68, nombre: 'Chave de Fenda', color: '#D0D4D6', vivax: '718', imagen: '/path/to/balde_chave_de_fenda.png' },
    { id: 69, nombre: 'Fio Metalizado', color: '#CACCD1', vivax: '722', imagen: '/path/to/balde_fio_metalizado.png' },
    { id: 70, nombre: 'Vapor de Água', color: '#BFC4C8', vivax: '743', imagen: '/path/to/balde_vapor_de_agua.png' },
    { id: 71, nombre: 'Carnaval', color: '#F77315', vivax: 'N/A', imagen: '/path/to/balde_carnaval.png' },
    { id: 72, nombre: 'Azul Glacial', color: '#58AFD5', vivax: '776', imagen: '/path/to/balde_azul_glacial.png' },
    { id: 73, nombre: 'Apatita', color: '#43BECA', vivax: '735', imagen: '/path/to/balde_apatita.png' }
  ];

  export default cor;